#   ______    __                                __       __
#  /      \  |  \                              |  \     |  \
# |  ▓▓▓▓▓▓\_| ▓▓_    ______   ______   _______| ▓▓____  \▓▓ ______
# | ▓▓___\▓▓   ▓▓ \  |      \ /      \ /       \ ▓▓    \|  \/      \
#  \▓▓    \ \▓▓▓▓▓▓   \▓▓▓▓▓▓\  ▓▓▓▓▓▓\  ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
#  _\▓▓▓▓▓▓\ | ▓▓ __ /      ▓▓ ▓▓   \▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓  | ▓▓
# |  \__| ▓▓ | ▓▓|  \  ▓▓▓▓▓▓▓ ▓▓      _\▓▓▓▓▓▓\ ▓▓  | ▓▓ ▓▓ ▓▓__/ ▓▓
#  \▓▓    ▓▓  \▓▓  ▓▓\▓▓    ▓▓ ▓▓     |       ▓▓ ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
#   \▓▓▓▓▓▓    \▓▓▓▓  \▓▓▓▓▓▓▓\▓▓      \▓▓▓▓▓▓▓ \▓▓   \▓▓\▓▓ ▓▓▓▓▓▓▓
#                                                          | ▓▓
#                                                          | ▓▓
#                                                           \▓▓

format = """
[ ](base15)\
$os\
$username\
$hostname\
[](bg:base10 fg:base15)\
$directory\
[](fg:base10 bg:base12)\
$git_branch\
$git_status\
[](fg:base12 bg:base13)\
$c\
$conda\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:base13 bg:base03)\
$docker_context\
[](fg:base03 bg:base01)\
[ ](fg:base01)\
\n$character
"""

# [ ](fg:blue)\

# move the rest of the prompt to the right
# right_format = """$all"""

# Disable the blank line at the start of the prompt
# add_newline = false

palette = 'rose-pine-dawn'

[palettes.gruvbox_dark]
base00 = '#fbf1c7'
base01 = '#3c3836'
base03 = '#665c54'
base13 = '#458588'
base12 = '#689d6a'
base11 = '#98971a'
base15 = '#d65d0e'
base14 = '#b16286'
base08 = '#cc241d'
base10 = '#d79921'

[palettes.gruvbox_dark_med]
base00 = '#282828' # ----
base01 = '#3c3836' # ---
base02 = '#504945' # --
base03 = '#665c54' # -
base04 = '#bdae93' # +
base05 = '#d5c4a1' # ++
base06 = '#ebdbb2' # +++
base07 = '#fbf1c7' # ++++
base08 = '#fb4934' # red
base09 = '#fe8019' # orange
base10 = '#fabd2f' # yellow
base11 = '#b8bb26' # green
base12 = '#8ec07c' # aqua/cyan
base13 = '#83a598' # blue
base14 = '#d3869b' # purple
base15 = '#d65d0e' # brown

[palettes.gruvbox_light_med]
base00 = '#fbf1c7' # ----
base01 = '#ebdbb2' # ---
base02 = '#d5c4a1' # --
base03 = '#bdae93' # -
base04 = '#665c54' # +
base05 = '#504945' # ++
base06 = '#3c3836' # +++
base07 = '#282828' # ++++
base08 = '#9d0006' # red
base09 = '#af3a03' # orange
base10 = '#b57614' # yellow
base11 = '#79740e' # green
base12 = '#427b58' # aqua/cyan
base13 = '#076678' # blue
base14 = '#8f3f71' # purple
base15 = '#d65d0e' # brown

[palettes.rose-pine-dawn]
base00 = '#faf4ed' # base
base01 = '#fffaf3' # surface
base02 = '#f2e9de' # overlay
base03 = '#9893a5' # muted
base04 = '#797593' # subtle
base05 = '#575279' # text
base06 = '#575279'
base07 = '#cecacd' # highlight high
base08 = '#b4637a' # love
base09 = '#ea9d34' # gold
base10 = '#d7827e' # rose
base11 = '#286983' # pine
base12 = '#56949f' # foam
base13 = '#907aa9' # iris
base14 = '#ea9d34'
base15 = '#cecacd'

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "fg:base00 bg:base15"
format = "[ $symbol ]($style)"
disabled = false               # Disabled by default

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:base00 bg:base15"
style_root = "fg:base00 bg:base15"
format = '[$user ]($style)'

[directory]
style = "fg:base00 bg:base10"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:

[character]
disabled = false
success_symbol = '[](bold fg:base11)'
error_symbol = '[](bold fg:base08)'
vimcmd_symbol = '[](bold fg:base11)'
vimcmd_replace_one_symbol = '[](bold fg:base14)'
vimcmd_replace_symbol = '[](bold fg:base14)'
vimcmd_visual_symbol = '[](bold fg:base10)'

[c]
symbol = " "
style = "bg:base13"
format = '[[ $symbol( $version) ](fg:base00 bg:base13)]($style)'

[conda]
disabled = false

[docker_context]
symbol = " "
style = "bg:base03"
format = '[[ $symbol( $context) ](fg:#83a598 bg:base03)]($style)'

[elixir]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[elm]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[git_branch]
symbol = ""
style = "bg:base12"
format = '[[ $symbol $branch ](fg:base00 bg:base12)]($style)'

[git_status]
style = "bg:base12"
format = '[[($all_status$ahead_behind )](fg:base00 bg:base12)]($style)'

[golang]
symbol = ""
style = "bg:base13"
format = '[[ $symbol( $version) ](fg:base00 bg:base13)]($style)'

[haskell]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[java]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[julia]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[hostname]
ssh_only = false
style = "fg:base00 bg:base15"
format = '[$ssh_symbol](bold fg:base07 bg:base15)[ on $hostname ]($style)'
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[nodejs]
symbol = ""
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[nim]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[python]
symbol = " "
style = "bg:base13"
format = '[[ $symbol( $version) ](fg:base00 bg:base13)]($style)'

[rust]
symbol = ""
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[time]
disabled = true
time_format = "%R"                                      # Hour:Minute Format
style = "fg:#11111b bg:#89b4fa"
format = '[[  $time ](fg:#11111b bg:#89b4fa)]($style)'
