#   ______    __                                __       __
#  /      \  |  \                              |  \     |  \
# |  ▓▓▓▓▓▓\_| ▓▓_    ______   ______   _______| ▓▓____  \▓▓ ______
# | ▓▓___\▓▓   ▓▓ \  |      \ /      \ /       \ ▓▓    \|  \/      \
#  \▓▓    \ \▓▓▓▓▓▓   \▓▓▓▓▓▓\  ▓▓▓▓▓▓\  ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
#  _\▓▓▓▓▓▓\ | ▓▓ __ /      ▓▓ ▓▓   \▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓  | ▓▓
# |  \__| ▓▓ | ▓▓|  \  ▓▓▓▓▓▓▓ ▓▓      _\▓▓▓▓▓▓\ ▓▓  | ▓▓ ▓▓ ▓▓__/ ▓▓
#  \▓▓    ▓▓  \▓▓  ▓▓\▓▓    ▓▓ ▓▓     |       ▓▓ ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
#   \▓▓▓▓▓▓    \▓▓▓▓  \▓▓▓▓▓▓▓\▓▓      \▓▓▓▓▓▓▓ \▓▓   \▓▓\▓▓ ▓▓▓▓▓▓▓
#                                                          | ▓▓
#                                                          | ▓▓
#                                                           \▓▓

format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$c\
$conda\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:color_blue bg:color_bg3)\
$docker_context\
[](fg:color_bg3 bg:color_bg1)\
[ ](fg:color_bg1)\
\n$character
"""

# [ ](fg:blue)\

# move the rest of the prompt to the right
# right_format = """$all"""

# Disable the blank line at the start of the prompt
# add_newline = false

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "fg:color_fg0 bg:color_orange"
format = "[ $symbol ]($style)"
disabled = false # Disabled by default

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:color_fg0 bg:color_orange"
style_root = "fg:color_fg0 bg:#color_orange"
format = '[$user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = " "
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[elixir]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[elm]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[java]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[julia]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[hostname]
ssh_only = true
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[nodejs]
symbol = ""
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[nim]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[python]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "fg:#11111b bg:#89b4fa"
format = '[[  $time ](fg:#11111b bg:#89b4fa)]($style)'
