# https://prettier.io/docs/en/configuration
# https://prettier.io/docs/en/options
#
# Markdown file settings
overrides:
  - files: "*.md"
    options:
      proseWrap: "always"
      printWidth: 80
      #tabWidth: 4
